apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: adhp/zkc-frontend
  newName: adhp/frontend
  newTag: zkc-main-020f29e
- name: denartcc/api
  newName: adhp/api
  newTag: dev-f961c5b
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
