apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-zkcartcc-org-tls
spec:
  dnsNames:
  - api.zkcartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: api-zkcartcc-org-tls
