apiVersion: v1
kind: ConfigMap
metadata:
  name: email-templates
data:
  inactive_warning.tmpl: |
    Subject: You are about to be inactive
    CC:
    - management@zkcartcc.org
    Body: |
      Dear {{.FirstName}} {{.LastName}},

      <p>This is a warning that you have not yet controlled the minimum number of hours during the activity as
      required by the Kansas City ARTCC General Facility SOP.  Per the policy, controllers must control 
      no less than 3 hours per quarter.</p>

      <p>If this requirement is not met, you will be marked inactive and are subject to
      removal from the roster. If you are unable to meet this requirement, please contact the Senior Staff to request
      a leave of absence. They may be contacted by emailing management@zkcartcc.org.</p>

      <p>Thanks,<br>
      {{- range $atm := findRole "atm"  -}}
      {{ $atm }}<br>
      {{- end -}}
      {{- range $datm := findRole "datm"  -}}
      {{ $datm }}<br>
      {{- end -}}
      Kansas City ARTCC, VATUSA<br>
      https://zkcartcc.org</p>
  inactive.tmpl: |
    Subject: You are inactive
    CC:
    - management@zkcartcc.org
    Body: |
      Dear {{.FirstName}} {{.LastName}},

      <p>This is an email notification to inform you that you have not met the minimum activity requirements as set forth
      by the Kansas City ARTCC General Facility SOP.  Per the policy, controllers must control no less than 3
      hours per quarter. You have been marked inactive on the roster and are subject to removal for inactivity.</p>

      <p>If you require a Leave of Absense, please contact the Senior Staff as soon as possible. They may be contacted by
      emailing management@zkcartcc.org.</p>

      <p>Thanks,<br>
      {{- range $atm := findRole "atm" -}}
      {{ $atm }}<br>
      {{- end -}}
      {{- range $datm := findRole "datm"  -}}
      {{ $datm }}<br>
      {{- end -}}
      Kansas City ARTCC, VATUSA<br>
      https://zkcartcc.org</p>
  visiting_rejected.tmpl: |
    Subject: Your visiting controller request has been rejected
    CC:
    - management@zkcartcc.org
    Body: |
      Dear {{.FirstName}} {{.LastName}},

      <p>This email is to notify you that your request to join the Kansas City ARTCC Visiting Controller Roster has been
      rejected. If you feel this was done in error, please reach out to the Kansas City ARTCC Senior Staff by emailing
      management@zkcartcc.org.</p>

      <p>The general reason applications are rejected are due to you not meeting the minimum requirements as listed on the
      website.</p>

      <p>Regards,<br>
      {{- range $atm := findRole "atm"  -}}
      {{ $atm }}<br>
      {{- end -}}
      {{- range $datm := findRole "datm"  -}}
      {{ $datm }}<br>
      {{- end -}}
      Kansas City ARTCC, VATUSA<br>
      https://zkcartcc.org</p>
  visiting_added.tmpl: |
    Subject: You have been added to the visiting controller roster
    CC:
    - management@zkcartcc.org
    Body: |
      Dear {{.FirstName}} {{.LastName}},

      <p>This email is to notify you that you have been added to the Kansas City ARTCC Visiting Controller Roster.</p>

      <p>We are thrilled to welcome you to Kansas City ARTCC on VATSIM.</p>

      <p>To get started, please visit our website at https://zkcartcc.org and log in using your VATSIM account. Our primary 
      communication platform is Discord, so if you don't already have it, please download it from this link. After downloading, 
      join our Discord server here: https://vats.im/zkcdiscord, and then link your Discord account to your ZKC 
      account by visiting https://discord.zkcartcc.org.</p>

      <p>Next, please review the Kansas City ARTCC Policies by visiting our website at https://zkcartcc.org.</p>

      <p>We look forward to controlling with you and hope to see you soon!<br>
      {{- range $atm := findRole "atm"  -}}
      {{ $atm }}<br>
      {{- end -}}
      {{- range $datm := findRole "datm"  -}}
      {{ $datm }}<br>
      {{- end -}}
      Kansas City ARTCC, VATUSA<br>
      https://zkcartcc.org</p>
  visiting_removed.tmpl: |
    Subject: You have been removed from the visiting controller roster
    CC:
    - management@zkcartcc.org
    Body: |
      Dear {{.FirstName}} {{.LastName}}

      <p>This is your notification that you have been removed from the Kansas City ARTCC Visiting Controller Roster. If you feel this
      was done in error, please reach out to the Kansas City ARTCC Senior Staff by emailing management@zkcartcc.org.</p>

      <p>Regards,<br>
      {{- range $atm := findRole "atm"  -}}
      {{ $atm }}<br>
      {{- end -}}
      {{- range $datm := findRole "datm"  -}}
      {{ $datm }}<br>
      {{- end -}}
      Kansas City ARTCC, VATUSA<br>
      https://zkcartcc.org</p>
