apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-zkcartcc-org-tls
spec:
  dnsNames:
  - www.zkcartcc.org
  - zkcartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: www-zkcartcc-org-tls
