apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-zkcartcc-org-tls
spec:
  dnsNames:
  - auth.zkcartcc.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-auth-zkcartcc-org
